version: "3.8"
services:

  # MySQL コンテナ
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  # Redmine コンテナ
  redmine:
    image: redmine:latest
    ports:
      - 33000:3000
    depends_on:
      - mysql
    volumes:
      - ./redmine-files:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: password
      REDMINE_DB_DATABASE: redmine